name: hastalik_analiz
description: "Domates yaprağı hastalık teşhis uygulaması"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  tflite_flutter: ^0.11.0
  image: ^4.5.2
  http: ^0.13.5
  shared_preferences: ^2.2.2
  flutter_animate: ^4.2.0
  geolocator: any
  permission_handler: any
  google_fonts: 4.0.4
  sqflite: ^2.3.0
  path: ^1.9.0
  fl_chart: ^0.63.0

  # 📌 Eklenenler:
  flutter_markdown: ^0.6.14
  share_plus: ^7.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/Bacterial_spot/
    - assets/images/Early_blight/
    - assets/images/Healthy/
    - assets/images/Late_blight/
    - assets/images/Leaf_Mold/
    - assets/images/Septoria_leaf_spot/
    - assets/images/Spider_mites_Two_spotted_spider_mite/
    - assets/images/Target_Spot/
    - assets/images/Tomato_mosaic_virus/
    - assets/images/Tomato_Yellow_Leaf_Curl_Virus/
    - assets/data/
    - assets/data/domates_hastaliklari_professional_final.json
    - assets/data/labels_with_description_v2.json
    - assets/data/domates_hastaliklari_genisletilmis.json
    - assets/images/wallpaper/arka_ana.jpg
    - assets/images/wallpaper/arka_analiz.jpg
    - assets/images/wallpaper/arka_bert.jpg
    - assets/images/wallpaper/arka_gecmis.jpg
    - assets/images/wallpaper/arka_kutuphane.jpg
