name: hastalik_analiz
description: "Domates yaprağı hastalık teşhis uygulaması"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  tflite_flutter: ^0.11.0
  image: ^4.5.2
  http: ^0.13.5
  shared_preferences: ^2.2.2
  flutter_animate: ^4.2.0
  geolocator: any
  permission_handler: any
  google_fonts: 4.0.4
  sqflite: ^2.3.0
  path: ^1.9.0
  fl_chart: ^0.63.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/data/
    - assets/data/domates_hastaliklari_detayli.json
    - assets/data/labels_with_description_v2.json
    - assets/data/domates_hastaliklari_genisletilmis.json
    - assets/data/labels_with_description_v2.json
